import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://automationexercise.com/")
    expect(page.get_by_role("heading", name="AutomationExercise")).to_be_visible()
    page.get_by_role("link", name=" Signup / Login").click()
    expect(page.get_by_role("heading", name="New User Signup!")).to_be_visible()
    page.get_by_role("textbox", name="Name").click()
    page.get_by_role("textbox", name="Name").fill("test")
    page.get_by_role("textbox", name="Name").press("Tab")
    page.locator("form").filter(has_text="Signup").get_by_placeholder("Email Address").fill("test@gmail.com")
    page.get_by_role("button", name="Signup").click()
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").click()
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").click()
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowLeft")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowLeft")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowLeft")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowLeft")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowLeft")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowLeft")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowRight")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").press("ArrowRight")
    page.locator("form").filter(has_text="Email Address already exist!").get_by_placeholder("Email Address").fill("test@fakemail.com")
    page.get_by_role("button", name="Signup").click()
    expect(page.get_by_text("Enter Account Information")).to_be_visible()
    page.get_by_text("Mr.").click()
    page.get_by_role("radio", name="Mr.").check()
    page.get_by_role("textbox", name="Password *").click()
    page.get_by_role("textbox", name="Password *").fill("test")
    page.locator("#days").select_option("23")
    page.locator("#months").select_option("8")
    page.locator("#years").select_option("2006")
    page.get_by_role("checkbox", name="Sign up for our newsletter!").check()
    page.get_by_role("checkbox", name="Receive special offers from").check()
    page.get_by_role("textbox", name="First name *").click()
    page.get_by_role("textbox", name="First name *").fill("test")
    page.get_by_role("textbox", name="First name *").press("Tab")
    page.get_by_role("textbox", name="Last name *").fill("testlast")
    page.get_by_role("textbox", name="Company", exact=True).click()
    page.get_by_role("textbox", name="Company", exact=True).fill("testcompany")
    page.get_by_role("textbox", name="Address * (Street address, P.").click()
    page.get_by_role("textbox", name="Address * (Street address, P.").fill("test adress 1")
    page.get_by_role("textbox", name="Address 2").click()
    page.get_by_role("textbox", name="Address 2").fill("test address 2")
    page.get_by_role("textbox", name="State *").click()
    page.get_by_role("textbox", name="State *").fill("gujrat")
    page.get_by_role("textbox", name="State *").press("Tab")
    page.get_by_role("textbox", name="City * Zipcode *").fill("ahmedabad")
    page.locator("#zipcode").click()
    page.locator("#zipcode").fill("368002")
    page.get_by_role("textbox", name="Mobile Number *").click()
    page.get_by_role("textbox", name="Mobile Number *").fill("11111111")
    page.get_by_role("button", name="Create Account").click()
    expect(page.get_by_text("Account Created!")).to_be_visible()
    page.get_by_role("link", name="Continue").click()
    expect(page.get_by_text("Logged in as test")).to_be_visible()
    page.get_by_role("link", name=" Delete Account").click()
    expect(page.get_by_text("Account Deleted!")).to_be_visible()
    page.get_by_role("link", name="Continue").click()
    page.goto("https://automationexercise.com/")



    page.locator("iframe[name=\"aswift_3\"]").content_frame.get_by_role("button", name="Close ad")
    page.locator("iframe[name=\"aswift_3\"]").content_frame.get_by_role("button", name="Close ad")
    page.locator("iframe[name=\"aswift_1\"]").content_frame.get_by_role("button", name="Close ad")


